SDFAT_FOLDER ?= external/sdfat

SDFAT_MODULE:
	make clean -C $(SDFAT_FOLDER) KDIR=$(KERNEL_OUT)
	make -j8 -C $(SDFAT_FOLDER) ARCH=arm KDIR=$(KERNEL_OUT) \
		$(if $(ARM_CROSS_COMPILE),$(ARM_CROSS_COMPILE),$(KERNEL_CROSS_COMPILE))
	mv $(SDFAT_FOLDER)/sdfat_fs.ko $(KERNEL_MODULES_OUT)
	$(if $(ARM_EABI_TOOLCHAIN),$(ARM_EABI_TOOLCHAIN)/arm-eabi-strip, \
		$(KERNEL_TOOLCHAIN_PATH)strip) --strip-unneeded $(KERNEL_MODULES_OUT)/sdfat_fs.ko

TARGET_KERNEL_MODULES += SDFAT_MODULE
